package com.jar.jarstacker.client.gui;

import com.jar.jarstacker.config.ModConfig;
import com.jar.jarstacker.network.JarStackerPackets;
import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.BooleanControllerBuilder;
import dev.isxander.yacl3.api.controller.DoubleSliderControllerBuilder;
import dev.isxander.yacl3.api.controller.IntegerFieldControllerBuilder;
import dev.isxander.yacl3.api.controller.IntegerSliderControllerBuilder;
import dev.isxander.yacl3.api.controller.StringControllerBuilder;
import net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

public class JarStackerYaclScreen {

	public static Screen buildScreen(Screen parent, ModConfig sourceConfig, long baseRevision) {
		ModConfig model = ModConfig.fromJson(sourceConfig.toJson());

		return YetAnotherConfigLib.createBuilder()
			.title(Component.literal("Jar Stacker Configuration"))
			.save(() -> {
				model.validate();
				Minecraft mc = Minecraft.getInstance();
				if (mc.isSingleplayer() || mc.level == null) {
					ModConfig.setInstance(model);
					ModConfig.save();
					if (mc.player != null) {
						mc.player.displayClientMessage(Component.literal("[Jar Stacker] Configuration saved!"), false);
					}
				} else {
					ClientPlayNetworking.send(new JarStackerPackets.ConfigUpdatePayload(baseRevision, model.toJson()));
				}
			})
			.category(ConfigCategory.createBuilder()
				.name(Component.literal("Items"))
				.tooltip(Component.literal("Configure dropped item stacking rules and limits"))
				.option(Option.<Boolean>createBuilder()
					.name(Component.literal("Enable Item Stacking"))
					.description(OptionDescription.of(Component.literal("Combine nearby compatible dropped items into logical stacks.")))
					.binding(true, () -> model.getItemStacking().isEnabled(), v -> model.getItemStacking().setEnabled(v))
					.controller(BooleanControllerBuilder::create)
					.build())
				.option(Option.<Double>createBuilder()
					.name(Component.literal("Stacking Radius"))
					.description(OptionDescription.of(Component.literal("Maximum distance in blocks to search for mergeable items.")))
					.binding(4.0, () -> model.getItemStacking().getRadius(), v -> model.getItemStacking().setRadius(v))
					.controller(opt -> DoubleSliderControllerBuilder.create(opt).range(1.0, 16.0).step(0.5))
					.build())
				.option(Option.<Integer>createBuilder()
					.name(Component.literal("Scan Interval (Ticks)"))
					.description(OptionDescription.of(Component.literal("Frequency of item scanning in ticks (20 ticks = 1 second).")))
					.binding(10, () -> model.getItemStacking().getScanIntervalTicks(), v -> model.getItemStacking().setScanIntervalTicks(v))
					.controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 100).step(1))
					.build())
				.option(Option.<Integer>createBuilder()
					.name(Component.literal("Maximum Stack Size"))
					.description(OptionDescription.of(Component.literal("Maximum logical items per stack entity (default: 4096).")))
					.binding(4096, () -> model.getItemStacking().getMaxStackSize(), v -> model.getItemStacking().setMaxStackSize(v))
					.controller(opt -> IntegerFieldControllerBuilder.create(opt).min(1).max(65536))
					.build())
				.option(Option.<Boolean>createBuilder()
					.name(Component.literal("Stack Unstackable Items"))
					.description(OptionDescription.of(Component.literal("Allow normally unstackable items (e.g. tools, weapons) to merge if identical.")))
					.binding(false, () -> model.getItemStacking().isStackUnstackableItems(), v -> model.getItemStacking().setStackUnstackableItems(v))
					.controller(BooleanControllerBuilder::create)
					.build())
				.option(Option.<Boolean>createBuilder()
					.name(Component.literal("Show Item Labels"))
					.description(OptionDescription.of(Component.literal("Display custom name tags on stacked item entities.")))
					.binding(true, () -> model.getItemStacking().isShowLabel(), v -> model.getItemStacking().setShowLabel(v))
					.controller(BooleanControllerBuilder::create)
					.build())
				.option(Option.<String>createBuilder()
					.name(Component.literal("Item Filter Mode"))
					.description(OptionDescription.of(Component.literal("BLACKLIST (stack all except blacklist) or WHITELIST (only stack whitelist).")))
					.binding("BLACKLIST", () -> model.getItemStacking().getFilterMode(), v -> model.getItemStacking().setFilterMode(v))
					.controller(StringControllerBuilder::create)
					.build())
				.build())
			.category(ConfigCategory.createBuilder()
				.name(Component.literal("Mobs"))
				.tooltip(Component.literal("Configure living mob stacking rules and limits"))
				.option(Option.<Boolean>createBuilder()
					.name(Component.literal("Enable Mob Stacking"))
					.description(OptionDescription.of(Component.literal("Combine nearby compatible living mobs into logical stacks.")))
					.binding(true, () -> model.getMobStacking().isEnabled(), v -> model.getMobStacking().setEnabled(v))
					.controller(BooleanControllerBuilder::create)
					.build())
				.option(Option.<Double>createBuilder()
					.name(Component.literal("Stacking Radius"))
					.description(OptionDescription.of(Component.literal("Maximum distance in blocks to search for mergeable mobs.")))
					.binding(6.0, () -> model.getMobStacking().getRadius(), v -> model.getMobStacking().setRadius(v))
					.controller(opt -> DoubleSliderControllerBuilder.create(opt).range(1.0, 32.0).step(0.5))
					.build())
				.option(Option.<Integer>createBuilder()
					.name(Component.literal("Scan Interval (Ticks)"))
					.description(OptionDescription.of(Component.literal("Frequency of mob scanning in ticks (20 ticks = 1 second).")))
					.binding(20, () -> model.getMobStacking().getScanIntervalTicks(), v -> model.getMobStacking().setScanIntervalTicks(v))
					.controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 100).step(1))
					.build())
				.option(Option.<Integer>createBuilder()
					.name(Component.literal("Maximum Stack Size"))
					.description(OptionDescription.of(Component.literal("Maximum logical mobs per representative entity (default: 256).")))
					.binding(256, () -> model.getMobStacking().getMaxStackSize(), v -> model.getMobStacking().setMaxStackSize(v))
					.controller(opt -> IntegerFieldControllerBuilder.create(opt).min(1).max(2048))
					.build())
				.option(Option.<Boolean>createBuilder()
					.name(Component.literal("Show Mob Labels"))
					.description(OptionDescription.of(Component.literal("Display custom name tags showing mob count.")))
					.binding(true, () -> model.getMobStacking().isShowLabel(), v -> model.getMobStacking().setShowLabel(v))
					.controller(BooleanControllerBuilder::create)
					.build())
				.option(Option.<String>createBuilder()
					.name(Component.literal("Mob Filter Mode"))
					.description(OptionDescription.of(Component.literal("BLACKLIST (stack all except blacklist) or WHITELIST (only stack whitelist).")))
					.binding("BLACKLIST", () -> model.getMobStacking().getFilterMode(), v -> model.getMobStacking().setFilterMode(v))
					.controller(StringControllerBuilder::create)
					.build())
				.build())
			.category(ConfigCategory.createBuilder()
				.name(Component.literal("Filters & Rules"))
				.tooltip(Component.literal("Manage whitelists, blacklists, and per-entity rules"))
				.option(ButtonOption.createBuilder()
					.name(Component.literal("Item Blacklist (" + model.getItemStacking().getBlacklist().size() + " entries)"))
					.description(OptionDescription.of(Component.literal("Configure items explicitly excluded from stacking.")))
					.action((screen, opt) -> Minecraft.getInstance().setScreen(
						new JarStackerConfigScreen.ListEditorScreen(screen, "Item Blacklist", model.getItemStacking().getBlacklist(), true)
					))
					.build())
				.option(ButtonOption.createBuilder()
					.name(Component.literal("Item Whitelist (" + model.getItemStacking().getWhitelist().size() + " entries)"))
					.description(OptionDescription.of(Component.literal("Configure items explicitly permitted when filter is WHITELIST.")))
					.action((screen, opt) -> Minecraft.getInstance().setScreen(
						new JarStackerConfigScreen.ListEditorScreen(screen, "Item Whitelist", model.getItemStacking().getWhitelist(), true)
					))
					.build())
				.option(ButtonOption.createBuilder()
					.name(Component.literal("Mob Blacklist (" + model.getMobStacking().getBlacklist().size() + " entries)"))
					.description(OptionDescription.of(Component.literal("Configure mobs explicitly excluded from stacking.")))
					.action((screen, opt) -> Minecraft.getInstance().setScreen(
						new JarStackerConfigScreen.ListEditorScreen(screen, "Mob Blacklist", model.getMobStacking().getBlacklist(), false)
					))
					.build())
				.option(ButtonOption.createBuilder()
					.name(Component.literal("Mob Whitelist (" + model.getMobStacking().getWhitelist().size() + " entries)"))
					.description(OptionDescription.of(Component.literal("Configure mobs explicitly permitted when filter is WHITELIST.")))
					.action((screen, opt) -> Minecraft.getInstance().setScreen(
						new JarStackerConfigScreen.ListEditorScreen(screen, "Mob Whitelist", model.getMobStacking().getWhitelist(), false)
					))
					.build())
				.option(ButtonOption.createBuilder()
					.name(Component.literal("Per-Item Rules (" + model.getItemStacking().getRules().size() + " rules)"))
					.description(OptionDescription.of(Component.literal("Configure custom maximum stack caps and limits for specific item IDs.")))
					.action((screen, opt) -> Minecraft.getInstance().setScreen(
						new JarStackerConfigScreen.ItemRulesScreen(screen, model)
					))
					.build())
				.option(ButtonOption.createBuilder()
					.name(Component.literal("Per-Mob Rules (" + model.getMobStacking().getRules().size() + " rules)"))
					.description(OptionDescription.of(Component.literal("Configure custom maximum stack caps and limits for specific mob IDs.")))
					.action((screen, opt) -> Minecraft.getInstance().setScreen(
						new JarStackerConfigScreen.MobRulesScreen(screen, model)
					))
					.build())
				.build())
			.category(ConfigCategory.createBuilder()
				.name(Component.literal("Display"))
				.tooltip(Component.literal("Configure entity stack labels"))
				.option(Option.<Boolean>createBuilder()
					.name(Component.literal("Show Item Labels"))
					.description(OptionDescription.of(Component.literal("Master toggle for item custom name labels.")))
					.binding(true, () -> model.getDisplay().isShowItemLabels(), v -> model.getDisplay().setShowItemLabels(v))
					.controller(BooleanControllerBuilder::create)
					.build())
				.option(Option.<Boolean>createBuilder()
					.name(Component.literal("Show Mob Labels"))
					.description(OptionDescription.of(Component.literal("Master toggle for mob custom name labels.")))
					.binding(true, () -> model.getDisplay().isShowMobLabels(), v -> model.getDisplay().setShowMobLabels(v))
					.controller(BooleanControllerBuilder::create)
					.build())
				.option(Option.<Boolean>createBuilder()
					.name(Component.literal("Hide Label When Count is 1"))
					.description(OptionDescription.of(Component.literal("If enabled, entities with count 1 show no label. If disabled, count 1 shows x1.")))
					.binding(true, () -> model.getDisplay().isShowCountOnlyWhenStacked(), v -> model.getDisplay().setShowCountOnlyWhenStacked(v))
					.controller(BooleanControllerBuilder::create)
					.build())
				.option(Option.<Integer>createBuilder()
					.name(Component.literal("Label Update Interval (Ticks)"))
					.description(OptionDescription.of(Component.literal("How often entity labels refresh.")))
					.binding(20, () -> model.getDisplay().getLabelUpdateIntervalTicks(), v -> model.getDisplay().setLabelUpdateIntervalTicks(v))
					.controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 100).step(1))
					.build())
				.build())
			.category(ConfigCategory.createBuilder()
				.name(Component.literal("Performance"))
				.tooltip(Component.literal("Configure logging and metrics"))
				.option(Option.<Boolean>createBuilder()
					.name(Component.literal("Debug Logging"))
					.description(OptionDescription.of(Component.literal("Log each merge event to server console.")))
					.binding(false, () -> model.getPerformance().isDebugLogging(), v -> model.getPerformance().setDebugLogging(v))
					.controller(BooleanControllerBuilder::create)
					.build())
				.option(Option.<Boolean>createBuilder()
					.name(Component.literal("Collect Metrics"))
					.description(OptionDescription.of(Component.literal("Track scan durations and rolling averages for /jarstacker status.")))
					.binding(true, () -> model.getPerformance().isCollectMetrics(), v -> model.getPerformance().setCollectMetrics(v))
					.controller(BooleanControllerBuilder::create)
					.build())
				.build())
			.build()
			.generateScreen(parent);
	}
}
