plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

repositories {
	maven { url 'https://maven.isxander.dev/releases' }
	maven { url 'https://maven.terraformersmc.com/releases/' }
}

loom {
	mods {
		"jarstacker" {
			sourceSet sourceSets.main
		}
	}
	runs {
		configureEach {
			runDir = rootProject.file("run").path
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	modImplementation "dev.isxander:yet-another-config-lib:${project.yacl_version}"
	modCompileOnly "com.terraformersmc:modmenu:${project.modmenu_version}"
	modLocalRuntime "com.terraformersmc:modmenu:${project.modmenu_version}"
}

version = "${project.mod_version}+mc${project.minecraft_version}"

base {
	archivesName = "jarstacker"
}

processResources {
	def modVer = project.mod_version
	def mcDep = project.hasProperty("minecraft_dependency") ? project.property("minecraft_dependency") : "~${project.minecraft_version}"
	def javaDep = project.hasProperty("java_dependency") ? project.property("java_dependency") : ">=21"
	inputs.property "version", modVer
	inputs.property "minecraft_dependency", mcDep
	inputs.property "java_dependency", javaDep

	filesMatching("fabric.mod.json") {
		expand([
			"version": modVer,
			"minecraft_dependency": mcDep,
			"java_dependency": javaDep
		])
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = (project.findProperty("java_version") ?: 21) as Integer
}

tasks.matching { it.name.startsWith("run") }.configureEach {
	if (project.hasProperty("runTests") || System.getProperty("jarstacker.test") != null) {
		systemProperty "jarstacker.test", "true"
	}
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}