pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

plugins {
	id 'dev.kikugie.stonecutter' version '0.9.8'
}

stonecutter {
	centralScript = "build.gradle"
	kotlinController = false

	create(rootProject) {
		versions("1.21.1", "1.21.2", "1.21.4", "1.21.5", "1.21.6", "1.21.9", "1.21.11")
	}
}

rootProject.name = 'jarstacker'
include 'runtime-test-1.21.3'
include 'runtime-test-1.21.7'
include 'runtime-test-1.21.8'
include 'runtime-test-1.21.10'