plugins {
	id 'fabric-loom' version '1.17.20'
}

repositories {
	mavenCentral()
	maven {
		name = 'Fabric'
		url = 'https://maven.fabricmc.net/'
	}
	maven {
		name = 'IsXander Maven'
		url = 'https://maven.isxander.dev/releases'
	}
	maven {
		name = 'TerraformersMC'
		url = 'https://maven.terraformersmc.com/releases'
	}
}

dependencies {
	minecraft "com.mojang:minecraft:1.21.8"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:0.19.3"
	modLocalRuntime "net.fabricmc.fabric-api:fabric-api:0.136.1+1.21.8"
	modLocalRuntime "dev.isxander:yet-another-config-lib:3.8.1+1.21.6-fabric"
	modLocalRuntime "com.terraformersmc:modmenu:15.0.2"
	def jarFile = file("${rootProject.projectDir}/versions/1.21.6/build/libs/jarstacker-0.7.0+mc1.21.6.jar")
	if (jarFile.exists()) {
		modLocalRuntime files(jarFile)
	}
}

loom {
	runs {
		server {
			runDir = rootProject.file("run").path
		}
		client {
			runDir = rootProject.file("run").path
		}
	}
}

tasks.matching { it.name.startsWith("run") }.configureEach {
	if (project.hasProperty("runTests") || System.getProperty("jarstacker.test") != null) {
		systemProperty "jarstacker.test", "true"
	}
}

