package com.jar.jarstacker.stack.mob;

import com.jar.jarstacker.config.ModConfig;
import com.jar.jarstacker.stack.StackableEntity;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.Mob;
import net.minecraft.world.entity.TamableAnimal;
//? if >=1.21.5 {
/*import net.minecraft.world.entity.animal.sheep.Sheep;
*///?} else {
import net.minecraft.world.entity.animal.Sheep;
import net.minecraft.world.entity.VariantHolder;
//?}
import net.minecraft.world.entity.monster.Creeper;
import net.minecraft.world.entity.monster.Shulker;
import net.minecraft.world.entity.monster.Slime;
import net.minecraft.world.item.ItemStack;

import java.util.Objects;
import java.util.Set;

public class MobCompatibility {
	private static final Set<EntityType<?>> EXCLUDED_TYPES = Set.of(
		EntityType.PLAYER,
		EntityType.ENDER_DRAGON,
		EntityType.WITHER,
		EntityType.ARMOR_STAND,
		EntityType.VILLAGER,
		EntityType.WANDERING_TRADER
	);

	public static class MobInspection {
		public final boolean stackable;
		public final String reason;

		public MobInspection(boolean stackable, String reason) {
			this.stackable = stackable;
			this.reason = reason;
		}
	}

	public static AnimalStackState getStackState(net.minecraft.world.entity.animal.Animal animal) {
		if (animal.isBaby()) {
			return AnimalStackState.BABY;
		} else if (animal.isInLove()) {
			return AnimalStackState.BREEDING_IN_LOVE;
		} else if (animal.getAge() > 0) {
			return AnimalStackState.BREEDING_COOLDOWN;
		} else {
			return AnimalStackState.ADULT;
		}
	}

	public static boolean hasDamageableEquipment(Mob mob) {
		if (mob == null) {
			return false;
		}
		for (EquipmentSlot slot : EquipmentSlot.values()) {
			ItemStack item = mob.getItemBySlot(slot);
			if (item != null && !item.isEmpty() && item.isDamageableItem()) {
				return true;
			}
		}
		return false;
	}

	public static boolean isDamageableItem(ItemStack item) {
		return item != null && !item.isEmpty() && item.isDamageableItem();
	}

	public static boolean isExcluded(Mob mob) {
		if (EXCLUDED_TYPES.contains(mob.getType())) {
			return true;
		}

		if (mob.isPassenger() || mob.isVehicle()) {
			return true;
		}

		if (mob instanceof TamableAnimal tamable && tamable.isTame()) {
			return true;
		}

		if (com.jar.jarstacker.adapter.EntityAdapter.isSaddled(mob)) {
			return true;
		}

		if (hasDamageableEquipment(mob)) {
			return true;
		}

		// If a mob has a custom name that was NOT generated by jarstacker, exclude it
		return isCustomNamedExclusion(mob);
	}

	public static boolean isManagedLabel(Mob mob) {
		if (mob == null || !mob.hasCustomName()) {
			return false;
		}
		return ((StackableEntity) mob).jarstacker$hasManagedLabel();
	}

	public static boolean isCustomNamedExclusion(Mob mob) {
		if (mob == null || !mob.hasCustomName()) {
			return false;
		}
		// If Jar Stacker manages this label, it is not a player custom name exclusion
		if (((StackableEntity) mob).jarstacker$hasManagedLabel()) {
			return false;
		}
		// It has a custom name not managed by Jar Stacker (e.g. player Name Tag)
		return true;
	}

	public static MobInspection inspectMob(Mob mob, ModConfig.MobStackingConfig config) {
		if (!mob.isAlive() || mob.isRemoved()) {
			return new MobInspection(false, "Entity is dead or removed");
		}
		if (EXCLUDED_TYPES.contains(mob.getType())) {
			return new MobInspection(false, "Entity type is hard-excluded for safety");
		}
		if (mob.isPassenger() || mob.isVehicle()) {
			return new MobInspection(false, "Entity has passenger or is riding");
		}
		if (mob instanceof TamableAnimal tamable && tamable.isTame()) {
			return new MobInspection(false, "Entity is tamed");
		}
		if (com.jar.jarstacker.adapter.EntityAdapter.isSaddled(mob)) {
			return new MobInspection(false, "Entity is saddled");
		}
		if (hasDamageableEquipment(mob)) {
			return new MobInspection(false, "Mob has damageable equipment");
		}
		if (isCustomNamedExclusion(mob)) {
			return new MobInspection(false, "Entity is custom named");
		}

		ResourceLocation key = BuiltInRegistries.ENTITY_TYPE.getKey(mob.getType());
		String mobId = key.toString();

		if ("BLACKLIST".equalsIgnoreCase(config.getFilterMode())) {
			if (config.getCachedBlacklist().contains(mobId)) {
				return new MobInspection(false, "Mob is in blacklist (" + mobId + ")");
			}
		} else if ("WHITELIST".equalsIgnoreCase(config.getFilterMode())) {
			if (!config.getCachedWhitelist().contains(mobId)) {
				return new MobInspection(false, "Mob is not in whitelist (" + mobId + ")");
			}
		}

		ModConfig.MobRuleConfig rule = config.getRules().get(mobId);
		if (rule != null && rule.getEnabled() != null && !rule.getEnabled()) {
			return new MobInspection(false, "Mob stacking disabled by per-mob rule (" + mobId + ")");
		}

		return new MobInspection(true, "Stackable");
	}

	public static double getRadius(Mob mob, ModConfig.MobStackingConfig config) {
		ResourceLocation key = BuiltInRegistries.ENTITY_TYPE.getKey(mob.getType());
		String mobId = key.toString();
		ModConfig.MobRuleConfig rule = config.getRules().get(mobId);
		if (rule != null && rule.getRadius() != null && rule.getRadius() > 0) {
			return rule.getRadius();
		}
		return config.getRadius();
	}

	public static int getMaxStackSize(Mob mob, ModConfig.MobStackingConfig config) {
		ResourceLocation key = BuiltInRegistries.ENTITY_TYPE.getKey(mob.getType());
		String mobId = key.toString();
		ModConfig.MobRuleConfig rule = config.getRules().get(mobId);
		if (rule != null && rule.getMaxStackSize() != null && rule.getMaxStackSize() > 0) {
			return rule.getMaxStackSize();
		}
		return config.getMaxStackSize();
	}

	public static boolean canStack(Mob a, Mob b, ModConfig.MobStackingConfig config) {
		if (!a.isAlive() || !b.isAlive() || a.isRemoved() || b.isRemoved()) {
			return false;
		}
		if (a == b) {
			return false;
		}

		if (a.getType() != b.getType()) {
			return false;
		}

		// Built-in safety exclusions are authoritative and cannot be bypassed
		if (isExcluded(a) || isExcluded(b)) {
			return false;
		}

		// Interaction / breeding lock: animals currently locked must not merge
		if (((StackableEntity) a).jarstacker$isInteractionLocked() || ((StackableEntity) b).jarstacker$isInteractionLocked()) {
			return false;
		}

		ResourceLocation key = BuiltInRegistries.ENTITY_TYPE.getKey(a.getType());
		String mobId = key.toString();

		// Whitelist / Blacklist
		if ("BLACKLIST".equalsIgnoreCase(config.getFilterMode())) {
			if (config.getCachedBlacklist().contains(mobId)) {
				return false;
			}
		} else if ("WHITELIST".equalsIgnoreCase(config.getFilterMode())) {
			if (!config.getCachedWhitelist().contains(mobId)) {
				return false;
			}
		}

		// Per-mob rule override
		ModConfig.MobRuleConfig rule = config.getRules().get(mobId);
		if (rule != null && rule.getEnabled() != null && !rule.getEnabled()) {
			return false;
		}

		if (a.isBaby() != b.isBaby()) {
			return false;
		}

		// Animal lifecycle states (BABY, BREEDING_IN_LOVE, BREEDING_COOLDOWN, ADULT)
		if (a instanceof net.minecraft.world.entity.animal.Animal aAnim && b instanceof net.minecraft.world.entity.animal.Animal bAnim) {
			if (getStackState(aAnim) != getStackState(bAnim)) {
				return false;
			}
		}

		// Variant check
		if (!com.jar.jarstacker.adapter.EntityAdapter.variantsMatch(a, b)) {
			return false;
		}

		// Sheep color & sheared state
		if (a instanceof Sheep sA && b instanceof Sheep sB) {
			if (sA.getColor() != sB.getColor() || sA.isSheared() != sB.isSheared()) {
				return false;
			}
		}

		// Snow Golem pumpkin state
		if (a instanceof net.minecraft.world.entity.animal.SnowGolem sgA && b instanceof net.minecraft.world.entity.animal.SnowGolem sgB) {
			if (sgA.hasPumpkin() != sgB.hasPumpkin()) {
				return false;
			}
		}

		// Mooshroom stew effects state
		if (a instanceof net.minecraft.world.entity.animal.MushroomCow mcA && b instanceof net.minecraft.world.entity.animal.MushroomCow mcB) {
			if (mcA.getVariant() != mcB.getVariant()) {
				return false;
			}
			net.minecraft.world.item.component.SuspiciousStewEffects stewA =
				((com.jar.jarstacker.mixin.MushroomCowAccessor) mcA).jarstacker$getStewEffects();
			net.minecraft.world.item.component.SuspiciousStewEffects stewB =
				((com.jar.jarstacker.mixin.MushroomCowAccessor) mcB).jarstacker$getStewEffects();
			boolean hasStewA = (stewA != null);
			boolean hasStewB = (stewB != null);
			if (hasStewA != hasStewB) {
				return false;
			}
			if (hasStewA && !Objects.equals(stewA, stewB)) {
				return false;
			}
		}

		// Strider cold state (suffocating)
		if (a instanceof net.minecraft.world.entity.monster.Strider stA && b instanceof net.minecraft.world.entity.monster.Strider stB) {
			if (stA.isSuffocating() != stB.isSuffocating()) {
				return false;
			}
		}

		// Creeper powered state
		if (a instanceof Creeper cA && b instanceof Creeper cB) {
			if (cA.isPowered() != cB.isPowered()) {
				return false;
			}
		}

		// Slime / Magma Cube size
		if (a instanceof Slime slA && b instanceof Slime slB) {
			if (slA.getSize() != slB.getSize()) {
				return false;
			}
		}

		// Shulker color
		if (a instanceof Shulker shA && b instanceof Shulker shB) {
			if (!Objects.equals(shA.getColor(), shB.getColor())) {
				return false;
			}
		}

		// Equipment check
		for (EquipmentSlot slot : EquipmentSlot.values()) {
			ItemStack itemA = a.getItemBySlot(slot);
			ItemStack itemB = b.getItemBySlot(slot);
			if (!ItemStack.isSameItemSameComponents(itemA, itemB)) {
				return false;
			}
		}

		return true;
	}

	public static String getIncompatibilityReason(Mob a, Mob b, ModConfig.MobStackingConfig config) {
		if (a == b) return "SAME_ENTITY";
		if (a.getType() != b.getType()) return "TYPE_MISMATCH";
		if (hasDamageableEquipment(a) || hasDamageableEquipment(b)) return "DAMAGEABLE_EQUIPMENT";
		if (isExcluded(a) || isExcluded(b)) return "EXCLUDED_MOB";
		if (((StackableEntity) a).jarstacker$isInteractionLocked() || ((StackableEntity) b).jarstacker$isInteractionLocked()) {
			return "INTERACTION_LOCKED";
		}
		if (a.isBaby() != b.isBaby()) return "BABY_STATE_MISMATCH";
		if (a instanceof net.minecraft.world.entity.animal.Animal aAnim && b instanceof net.minecraft.world.entity.animal.Animal bAnim) {
			if (getStackState(aAnim) != getStackState(bAnim)) return "LIFECYCLE_STATE_MISMATCH";
		}
		com.jar.jarstacker.adapter.EntityAdapter.VariantCompatibilityResult variantResult =
			com.jar.jarstacker.adapter.EntityAdapter.evaluateVariantCompatibility(a, b);
		if (variantResult == com.jar.jarstacker.adapter.EntityAdapter.VariantCompatibilityResult.MISMATCH) {
			return "VARIANT_MISMATCH";
		}
		if (variantResult == com.jar.jarstacker.adapter.EntityAdapter.VariantCompatibilityResult.UNKNOWN) {
			return "UNKNOWN_VARIANT_COMPATIBILITY";
		}
		if (a instanceof net.minecraft.world.entity.animal.MushroomCow mcA && b instanceof net.minecraft.world.entity.animal.MushroomCow mcB) {
			if (mcA.getVariant() != mcB.getVariant()) return "MOOSHROOM_VARIANT_MISMATCH";
			net.minecraft.world.item.component.SuspiciousStewEffects stewA =
				((com.jar.jarstacker.mixin.MushroomCowAccessor) mcA).jarstacker$getStewEffects();
			net.minecraft.world.item.component.SuspiciousStewEffects stewB =
				((com.jar.jarstacker.mixin.MushroomCowAccessor) mcB).jarstacker$getStewEffects();
			boolean hasStewA = (stewA != null);
			boolean hasStewB = (stewB != null);
			if (hasStewA != hasStewB) return "MOOSHROOM_STEW_STATE_MISMATCH";
			if (hasStewA && !Objects.equals(stewA, stewB)) return "MOOSHROOM_STEW_EFFECT_MISMATCH";
		}
		if (a instanceof Sheep sA && b instanceof Sheep sB) {
			if (sA.getColor() != sB.getColor()) return "SHEEP_COLOR_MISMATCH";
			if (sA.isSheared() != sB.isSheared()) return "SHEEP_SHEARED_MISMATCH";
		}
		if (a instanceof net.minecraft.world.entity.animal.SnowGolem sgA && b instanceof net.minecraft.world.entity.animal.SnowGolem sgB) {
			if (sgA.hasPumpkin() != sgB.hasPumpkin()) return "SNOW_GOLEM_PUMPKIN_MISMATCH";
		}
		if (a instanceof net.minecraft.world.entity.monster.Strider stA && b instanceof net.minecraft.world.entity.monster.Strider stB) {
			if (stA.isSuffocating() != stB.isSuffocating()) return "STRIDER_WARMTH_MISMATCH";
		}
		return "COMPATIBLE";
	}
}